# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-30 02:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=64, unique=True, verbose_name='用户名')),
                ('password', models.CharField(max_length=64, verbose_name='用户名')),
                ('uid', models.CharField(max_length=64, unique=True, verbose_name='个人唯一ID')),
                ('wx_id', models.CharField(blank=True, db_index=True, max_length=128, null=True, verbose_name='微信ID')),
            ],
        ),
    ]
